version: '3.9'

services:
  server:
    container_name: server
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
      - DB_HOST=db
    depends_on:
      - db
      - redis

  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  db:
    container_name: db
    restart: always
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shin-monta-no-mori
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7.4.0-alpine3.20
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data:
