version: '3.9'

services:
  server:
    container_name: shin-monta-no-mori-server
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
      - DB_HOST=db
    depends_on:
      - db

  client:
    container_name: shin-monta-no-mori-client
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: [ "npm", "run", "dev" ]

  db:
    container_name: shin-monta-no-mori-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shin-monta-no-mori
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx:1.27.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

volumes:
  postgres_data:
