ALTER TABLE "operators"
ALTER COLUMN "created_at"
SET DEFAULT 'now()';
ALTER TABLE "sessions"
ALTER COLUMN "created_at"
SET DEFAULT 'now()';
ALTER TABLE "images"
ALTER COLUMN "created_at"
SET DEFAULT 'now()';
ALTER TABLE "characters"
ALTER COLUMN "created_at"
SET DEFAULT 'now()';
ALTER TABLE "parent_categories"
ALTER COLUMN "created_at"
SET DEFAULT 'now()';
ALTER TABLE "child_categories"
ALTER COLUMN "created_at"
SET DEFAULT 'now()';
ALTER TABLE "images"
ALTER COLUMN "updated_at"
SET DEFAULT 'now()';
ALTER TABLE "characters"
ALTER COLUMN "updated_at"
SET DEFAULT 'now()';
ALTER TABLE "parent_categories"
ALTER COLUMN "updated_at"
SET DEFAULT 'now()';
ALTER TABLE "child_categories"
ALTER COLUMN "updated_at"
SET DEFAULT 'now()';