// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: characters.sql

package db

import (
	"context"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (name, src)
VALUES ($1, $2)
RETURNING id, name, src, updated_at, created_at
`

type CreateCharacterParams struct {
	Name string `json:"name"`
	Src  string `json:"src"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter, arg.Name, arg.Src)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Src,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, name, src, updated_at, created_at
FROM characters
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCharacter(ctx context.Context, id int64) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Src,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, name, src, updated_at, created_at
FROM characters
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListCharactersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCharacters(ctx context.Context, arg ListCharactersParams) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharacters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Src,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacter = `-- name: UpdateCharacter :one
UPDATE characters
SET name = $2,
  src = $3
WHERE id = $1
RETURNING id, name, src, updated_at, created_at
`

type UpdateCharacterParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Src  string `json:"src"`
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, updateCharacter, arg.ID, arg.Name, arg.Src)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Src,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
