// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: parent_categories.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createParentCategory = `-- name: CreateParentCategory :one
INSERT INTO parent_categories (name, src, filename)
VALUES ($1, $2, $3)
RETURNING id, name, src, updated_at, created_at, filename
`

type CreateParentCategoryParams struct {
	Name     string         `json:"name"`
	Src      string         `json:"src"`
	Filename sql.NullString `json:"filename"`
}

func (q *Queries) CreateParentCategory(ctx context.Context, arg CreateParentCategoryParams) (ParentCategory, error) {
	row := q.db.QueryRowContext(ctx, createParentCategory, arg.Name, arg.Src, arg.Filename)
	var i ParentCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Src,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Filename,
	)
	return i, err
}

const deleteParentCategory = `-- name: DeleteParentCategory :exec
DELETE FROM parent_categories
WHERE id = $1
`

func (q *Queries) DeleteParentCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteParentCategory, id)
	return err
}

const getParentCategory = `-- name: GetParentCategory :one
SELECT id, name, src, updated_at, created_at, filename
FROM parent_categories
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetParentCategory(ctx context.Context, id int64) (ParentCategory, error) {
	row := q.db.QueryRowContext(ctx, getParentCategory, id)
	var i ParentCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Src,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Filename,
	)
	return i, err
}

const listParentCategories = `-- name: ListParentCategories :many
SELECT id, name, src, updated_at, created_at, filename
FROM parent_categories
ORDER BY id DESC
`

func (q *Queries) ListParentCategories(ctx context.Context) ([]ParentCategory, error) {
	rows, err := q.db.QueryContext(ctx, listParentCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParentCategory{}
	for rows.Next() {
		var i ParentCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Src,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchParentCategories = `-- name: SearchParentCategories :many
SELECT DISTINCT id, name, src, updated_at, created_at, filename
FROM parent_categories
WHERE name LIKE '%' || COALESCE($1) || '%'
  OR filename LIKE '%' || COALESCE($1) || '%'
ORDER BY id DESC
`

func (q *Queries) SearchParentCategories(ctx context.Context, query sql.NullString) ([]ParentCategory, error) {
	rows, err := q.db.QueryContext(ctx, searchParentCategories, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParentCategory{}
	for rows.Next() {
		var i ParentCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Src,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParentCategory = `-- name: UpdateParentCategory :one
UPDATE parent_categories
SET name = $2,
  src = $3,
  filename = $4,
  updated_at = $5
WHERE id = $1
RETURNING id, name, src, updated_at, created_at, filename
`

type UpdateParentCategoryParams struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Src       string         `json:"src"`
	Filename  sql.NullString `json:"filename"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateParentCategory(ctx context.Context, arg UpdateParentCategoryParams) (ParentCategory, error) {
	row := q.db.QueryRowContext(ctx, updateParentCategory,
		arg.ID,
		arg.Name,
		arg.Src,
		arg.Filename,
		arg.UpdatedAt,
	)
	var i ParentCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Src,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Filename,
	)
	return i, err
}
