name: Go Test Coverage by Directory

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.go"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.2"
          cache: true
          cache-dependency-path: go.sum

      - name: OS Version
        run: cat /etc/os-release

      - name: Go Version
        run: go version

      # - name: Go Lint
      #   uses: golangci/golangci-lint-action@v3

      - name: Setup
        run: |
          go install github.com/golang/mock/mockgen@latest
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          go get github.com/onsi/gomega/...

      # - name: Regenerate mock file
      #   run: |
      #     rm -rf mock
      #     go generate ./...

      - name: Go Build
        run: |
          go build -v ./server/...

      - name: Go Test
        run: |
          ginkgo -v --cover --coverprofile=coverage.out --race --coverpkg=./server/... --covermode=atomic --output-dir=/tmp

      - name: Exclude auto-generated files from coverage
        run: |
          cat /tmp/coverage.out | grep -v "_mock.go" | grep -v ".pb.go" > coverage.out
          go tool cover -func coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          fail_ci_if_error: true
          verbose: true
