name: Go Test Coverage by Directory

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.go"

jobs:
  test_coverage:
    name: Go Test and Coverage Report
    runs-on: ubuntu-latest

    services:
      shin-monta-no-mori-db:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shin-monta-no-mori-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.2"

      - name: Run Go Test and generate coverage
        run: |
          mkdir -p coverage
          make test

      - name: Upload Coverage HTML
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/coverage.html

      - name: Post coverage results to PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Test Coverage Report
            ```plaintext
            $(cat coverage/report.txt)
            ```
            [Coverage Report HTML](https://github.com/${{ github.repository }}/actions/artifacts)
